use OIM;
DROP TABLE IF EXISTS OIM_INVENTORY_ITEMS;
DROP TABLE IF EXISTS OIM_INVENTORY_CATEGORY;
DROP TABLE IF EXISTS OIM_USERACCOUTNS;

CREATE TABLE OIM_USERACCOUTNS(USERNAME VARCHAR(25) PRIMARY KEY, FIRSTNAME VARCHAR(50) NOT NULL, LASTNAME VARCHAR(50) NOT NULL, ADDRESS VARCHAR(250) NOT NULL, EMAILID VARCHAR(150) NOT NULL, PHONENUMBER BIGINT(20) NOT NULL, PASSWORD VARCHAR(30) NOT NULL);


CREATE TABLE OIM_INVENTORY_CATEGORY(USERNAME VARCHAR(25),CATEGORY VARCHAR(25) PRIMARY KEY, YEAR int, SEASON VARCHAR(15),FOREIGN KEY (USERNAME) REFERENCES OIM_USERACCOUTNS(USERNAME));


CREATE TABLE OIM_INVENTORY_ITEMS( USERNAME VARCHAR(25),CATEGORY VARCHAR(25), ITEMNAME VARCHAR(50) PRIMARY KEY, PRODUCTION_COST INT, SELLING_COST INT,SIZEXS_AVAIL INT, SIZEXS_SOLD INT, SIZES_AVAIL INT, SIZES_SOLD INT, SIZEM_AVAIL INT, SIZEM_SOLD INT, SIZEL_AVAIL INT, SIZEL_SOLD INT,SIZEXL_AVAIL INT, SIZEXL_SOLD INT, SIZEXXL_AVAIL INT, SIZEXXL_SOLD INT, FOREIGN KEY (USERNAME) REFERENCES OIM_USERACCOUTNS(USERNAME), FOREIGN KEY (CATEGORY) REFERENCES OIM_INVENTORY_CATEGORY(CATEGORY));