DROP TABLE IF EXISTS INVETORY_SIZE;
DROP TABLE IF EXISTS OIM_INVENTORY_ITEMS;
DROP TABLE IF EXISTS OIM_INVENTORY_CATEGORY;
DROP TABLE IF EXISTS OIM_USERACCOUTNS;
CREATE TABLE OIM_USERACCOUTNS(USERNAME VARCHAR(25) PRIMARY KEY, FIRSTNAME VARCHAR(50) NOT NULL, LASTNAME VARCHAR(50) NOT NULL, ADDRESS VARCHAR(250) NOT NULL, EMAILID VARCHAR(150) NOT NULL, PHONENUMBER INT NOT NULL, PASSWORD VARCHAR(30) NOT NULL);


CREATE TABLE OIM_INVENTORY_CATEGORY(USERNAME VARCHAR(25),CATEGORY VARCHAR(25) PRIMARY KEY, YEAR int(4), SEASON VARCHAR(15),FOREIGN KEY (USERNAME) REFERENCES OIM_USERACCOUTNS(USERNAME));


CREATE TABLE OIM_INVENTORY_ITEMS( USERNAME VARCHAR(25),CATEGORY VARCHAR(25), ITEMNAME VARCHAR(50) PRIMARY KEY, PRODUCTION_COST INT(6), SELLING_COST INT(6), FOREIGN KEY (USERNAME) REFERENCES OIM_USERACCOUTNS(USERNAME), FOREIGN KEY (CATEGORY) REFERENCES OIM_INVENTORY_CATEGORY(CATEGORY));


CREATE TABLE OIM_INVENTORY_SIZES( USERNAME VARCHAR(25), CATEGORY VARCHAR(25), ITEMNAME VARCHAR(50), SIZE VARCHAR(25), AVAILABLE INT(5), SOLD INT(5), FOREIGN KEY (USERNAME) REFERENCES OIM_USERACCOUTNS(USERNAME), FOREIGN KEY (CATEGORY) REFERENCES OIM_INVENTORY_CATEGORY(CATEGORY), FOREIGN KEY (ITEMNAME) REFERENCES OIM_INVENTORY_ITEMS(ITEMNAME));